source 'http://rubygems.org/'

gem 'sinatra'
gem 'haml'
gem 'rack'
gem 'bundler'
gem 'mongoid', '2.0.0.rc.7'
gem 'bson_ext', '1.2.4'
gem 'mail'
gem 'mime'
gem 'iconv'
gem 'pony'
gem 'will_paginate'
gem 'rack-flash'